# Generated by Django 2.2.13 on 2020-11-24 15:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0015_auto_20181129_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='objectTagArea',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]