# Generated by Django 2.2.13 on 2020-12-03 21:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0016_areaofinterest_objecttagarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='filterStatus',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
